import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";

import HeaderPage from "./components/Header/page";

const notoSansBengali = Noto_Sans_Bengali({
  subsets: ["latin","bengali"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${notoSansBengali.className}  h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">
        <HeaderPage></HeaderPage>
        {children}
        </body>
    </html>
  );
}
